trigger:
- main

pool:
  name: Default

steps:
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'front-end'
    output_location: 'dist/medical-center'
    azure_static_web_apps_api_token: $(deployment_token)
  displayName: 'Deploy Angular App'